"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {AudioLines,ArrowDownToLine,Link2,Search,Square,FolderDown,Headphones,FileAudio,ExternalLink,LoaderCircle,Info} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import type {AudioFile} from '@/lib/audio';
type PageResult={url:string;title:string;state:'waiting'|'scanning'|'done'|'error';count:number;warnings:string[]};
const examples='https://www.xiaoyuzhoufm.com/episode/6a912c69f03e74ee6b01234f\nhttps://www.xiaoyuzhoufm.com/episode/6a97a9daa0210c197dcc1ba0\nhttps://www.bilibili.com/video/BV1hky1B4EW4/';
const bytes=(n:number)=>n?`${(n/1024/1024).toFixed(1)} MB`:'大小未知';
function parseInput(text:string){return [...new Set((text.match(/https?:\/\/[^\s<>"\[\]()]+/g)||[]).map(u=>u.replace(/[，。；]+$/,'')))];}
function downloadUrl(f:AudioFile){return '/api/download?'+new URLSearchParams({url:f.url,source:f.source,filename:f.filename,mode:f.mode||'direct'});}
export default function Home(){
 const [input,setInput]=useState(examples),[files,setFiles]=useState<AudioFile[]>([]),[pages,setPages]=useState<PageResult[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[playing,setPlaying]=useState<string|null>(null),[stopped,setStopped]=useState(false);
 const abort=useRef<AbortController|null>(null),active=useRef(false),audio=useRef<HTMLAudioElement|null>(null),frames=useRef<HTMLIFrameElement[]>([]);
 const urls=parseInput(input),completed=pages.filter(p=>p.state==='done'||p.state==='error').length,selectedFiles=files.filter(f=>selected.has(f.url)),total=files.reduce((n,f)=>n+f.size,0),extractCount=files.filter(f=>f.mode==='extract').length;
 const scan=useCallback(async(text:string)=>{
  const links=parseInput(text);if(!links.length){toast.error('请粘贴至少一个完整网页链接');return {error:'缺少链接'};}if(links.length>100){toast.error('每次最多扫描 100 个网页，请分批添加');return {error:'链接过多'};}if(active.current)return {error:'已有扫描正在进行'};
  active.current=true;const controller=new AbortController();abort.current=controller;setBusy(true);setStopped(false);setFiles([]);setSelected(new Set());audio.current?.pause();setPlaying(null);const result:AudioFile[]=[],seen=new Set<string>();let index=0;
  setPages(links.map(url=>({url,title:(()=>{try{return new URL(url).hostname;}catch{return url;}})(),state:'waiting',count:0,warnings:[]})));
  function patch(url:string,change:Partial<PageResult>){setPages(p=>p.map(x=>x.url===url?{...x,...change}:x));}
  await Promise.all(Array.from({length:Math.min(3,links.length)},async()=>{while(index<links.length&&!controller.signal.aborted){const url=links[index++];patch(url,{state:'scanning'});try{
   const r=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url}),signal:controller.signal}),d=await r.json() as {error?:string;files:AudioFile[];title:string;warnings?:string[]};if(!r.ok)throw new Error(d.error||'扫描失败');if(controller.signal.aborted)break;
   const additions=(d.files as AudioFile[]).filter(f=>{if(seen.has(f.url))return false;seen.add(f.url);return true;});result.push(...additions);setFiles([...result]);setSelected(s=>new Set([...s,...additions.map(f=>f.url)]));patch(url,{state:'done',title:d.title,count:d.files.length,warnings:d.warnings||[]});
  }catch(e){if(controller.signal.aborted)break;patch(url,{state:'error',warnings:[e instanceof Error?e.message:'扫描失败']});}}}));
  if(controller.signal.aborted){setStopped(true);setPages(p=>p.map(x=>['waiting','scanning'].includes(x.state)?{...x,state:'error',warnings:['扫描已停止，可重新扫描']}:x));toast('扫描已停止，已找到的音频仍可下载');}else toast.success(`扫描完成，找到 ${result.length} 个不同音频`);setBusy(false);active.current=false;return {files:result.map(f=>({title:f.title,url:f.url,format:f.format,size:f.size})),pageCount:links.length};
 },[]);
 useEffect(()=>{const lifecycle=new AbortController(),model=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<unknown>}}).modelContext;
  if(model?.registerTool)Promise.resolve(model.registerTool({name:'scan_audio_pages',description:'扫描公开音视频网页，识别音频直链或完整视频音轨，更新结果但不开始下载。',inputSchema:{type:'object',properties:{urls:{type:'array',items:{type:'string'},minItems:1,maxItems:100}},required:['urls'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(arg:unknown)=>{const x=arg as {urls?:unknown};if(!Array.isArray(x.urls)||!x.urls.length||x.urls.length>100||x.urls.some(u=>typeof u!=='string'||!/^https?:\/\//.test(u)))throw new Error('请输入 1–100 个完整网页链接');const value=x.urls.join('\n');setInput(value);return scan(value);}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>{lifecycle.abort();abort.current?.abort();for(const f of frames.current)f.remove();};
 },[scan]);
 function launch(action:string,manifest?:string){const frame=document.createElement('iframe');frame.hidden=true;frame.name='audio-download-'+crypto.randomUUID();document.body.appendChild(frame);frames.current.push(frame);frame.addEventListener('load',()=>{try{const msg=frame.contentDocument?.body?.textContent;if(msg?.trim())toast.error(msg.slice(0,220));}catch{}});
  if(manifest){const form=document.createElement('form');form.method='POST';form.action=action;form.target=frame.name;const field=document.createElement('input');field.type='hidden';field.name='manifest';field.value=manifest;form.appendChild(field);document.body.appendChild(form);form.submit();form.remove();}else frame.src=action;
 }
 function batch(){if(!selectedFiles.length)return;if(selectedFiles.length>100){toast.error('每个压缩包最多 100 个音频，请减少选择');return;}if(selectedFiles.reduce((n,f)=>n+f.size,0)>3*1024**3){toast.error('压缩包超过 3 GB，请减少选择并分批下载');return;}launch('/api/bundle',JSON.stringify(selectedFiles));toast('已开始打包下载，请在浏览器下载列表查看进度。异常文件会在压缩包中附带说明。',{duration:7000});}
 async function preview(f:AudioFile){if(playing===f.url){audio.current?.pause();setPlaying(null);return;}setPlaying(f.url);if(audio.current){audio.current.src=downloadUrl(f)+'&preview=1';try{await audio.current.play();}catch{setPlaying(null);toast.error('浏览器无法播放此格式，可直接下载');}}}
 const notices=pages.filter(p=>p.state==='error'||p.warnings.length);
 return <div className="app-shell"><Toaster position="bottom-right" richColors/><audio ref={audio} onEnded={()=>setPlaying(null)} onError={()=>{setPlaying(null);toast.error('试听加载失败，尝试直接下载');}} preload="none"/>
 <header className="topbar"><a href="/" className="brand" aria-label="拾音首页"><span className="brand-icon"><AudioLines size={23}/></span><strong>拾音</strong><span className="brand-en">AUDIO COLLECTOR</span></a><span className="top-caption"><Headphones size={16}/> 原始格式 · 原始音质</span></header>
 <main className="workspace"><div className="page-title"><div><p className="eyebrow">YOUR AUDIO, TO GO</p><h1>音频批量下载<span className="title-period">.</span></h1><p className="description">下载网页里的音频，也能提取视频里的完整声音。</p></div><div className="steps"><span><b>01</b> 粘贴链接</span><i/><span><b>02</b> 扫描音频</span><i/><span><b>03</b> 批量下载</span></div></div>
 <div className="main-grid"><section className="input-panel panel"><div className="panel-heading"><span className="section-number">01</span><h2>添加网页链接</h2><Link2 size={18}/></div><label className="input-label" htmlFor="page-urls">每行一个，也可以直接粘贴一整段链接</label><textarea id="page-urls" value={input} onChange={e=>setInput(e.target.value)} disabled={busy} spellCheck={false} placeholder={'https://www.xiaoyuzhoufm.com/episode/…\nhttps://example.com/audio-page'}/><div className="input-meta"><span>{urls.length} 个不同链接</span><Button variant="ghost" size="sm" disabled={busy||!input} onClick={()=>setInput('')}>清空</Button></div>
 <Button className="scan-button" disabled={!urls.length||busy} onClick={()=>scan(input)}>{busy?<LoaderCircle className="spin"/>:<Search/>}{busy?'正在寻找音频…':'扫描全部链接'}{!busy&&<span className="key-hint">→</span>}</Button>{busy&&<Button variant="outline" className="stop-button" onClick={()=>abort.current?.abort()}><Square/>停止扫描</Button>}
 <div className="support-note"><Info size={17}/><p>支持小宇宙、哔哩哔哩、公开媒体网页和直链。优先获取独立音轨，视频仅保存声音。</p></div><div className="formats">{['MP3','M4A','AAC','WAV','FLAC','OGG'].map(x=><span key={x}>{x}</span>)}</div><details className="limitations"><summary>哪些链接可能无法识别？</summary><p>需要登录、受保护内容或仅播放后加载的媒体，可能无法扫描。支持常见 MP4、WebM、MOV 和完整 HLS 回放；进行中的直播、静音视频和不支持的格式会显示原因。</p></details></section>
 <section className="result-panel panel"><div className="result-header"><div className="panel-heading"><span className="section-number">02</span><h2>发现的音频</h2><span className="result-count">{files.length}</span></div><Button variant="outline" className="batch-button" disabled={!selectedFiles.length||busy} onClick={batch}><FolderDown size={17}/>批量下载{selectedFiles.length>0&&<span>({selectedFiles.length})</span>}</Button></div>
 {(busy||pages.length>0)&&<div className="scan-status"><div><span>{busy?'正在扫描网页':stopped?'扫描已停止':'扫描完成'}</span><span>{completed} / {pages.length}</span></div><Progress value={pages.length?completed/pages.length*100:0} aria-label="网页扫描进度"/></div>}
 {files.length>0?<><div className="selection-bar"><label><Checkbox checked={selected.size===files.length?true:selected.size?'indeterminate':false} onCheckedChange={v=>setSelected(v?new Set(files.map(f=>f.url)):new Set())} aria-label="全选音频"/><span>已选 {selectedFiles.length} 个</span></label><span>{total?bytes(total):''}{extractCount>0&&(total?' + ':'')+extractCount+' 个音轨待提取'} · 自动去重</span></div><div className="audio-list"><Table><TableHeader className="sr-only"><TableRow><TableHead>选择</TableHead><TableHead>音频名称</TableHead><TableHead>下载</TableHead></TableRow></TableHeader><TableBody>{files.map((f,i)=><TableRow key={f.url}><TableCell className="choose-cell"><Checkbox checked={selected.has(f.url)} aria-label={'选择 '+f.title} onCheckedChange={v=>setSelected(s=>{const n=new Set(s);if(v)n.add(f.url);else n.delete(f.url);return n;})}/></TableCell><TableCell className="file-cell"><div className="file-info"><button type="button" className={'file-icon '+(playing===f.url?'playing':'')} onClick={()=>preview(f)} aria-label={(playing===f.url?'暂停':'试听')+f.title}>{playing===f.url?<AudioLines size={22}/>:<FileAudio size={23}/>}</button><div className="file-text"><div className="file-index">TRACK {String(i+1).padStart(2,'0')} {f.podcast&&<span>/ {f.podcast}</span>}</div><h3>{f.title}</h3><div className="file-meta"><span className="format-chip">{f.format.toUpperCase()}</span><span>{f.mode==='extract'?'完整音轨 · '+(f.sourceFormat==='独立音轨'?'独立音频':'视频提取'):bytes(f.size)}</span>{f.duration&&<span>{Math.round(f.duration/60)} 分钟</span>}<a href={f.source} target="_blank" rel="noreferrer">来源 <ExternalLink size={12}/></a></div></div></div></TableCell><TableCell className="download-cell"><Button variant="ghost" size="icon" aria-label={'下载 '+f.title} onClick={()=>{launch(downloadUrl(f));toast('已提交下载，请查看浏览器下载列表');}}><ArrowDownToLine size={20}/></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="download-note"><FolderDown size={16}/><span>视频会先提取声音，再与其他音频一起保存为 ZIP。</span></div></>:<div className="empty-result"><div className="empty-symbol"><AudioLines size={40}/></div><h3>{busy?'正在网页里寻找声音':pages.length?'暂未找到可下载音频':'你的下一份音频收藏'}</h3><p>{busy?'识别音频、检查链接，结果会逐条出现。':pages.length?'查看下方说明，或换一个公开网页链接。':'在左侧粘贴链接，点击扫描就能找到音频。'}</p><div className="empty-lines"><span/><span/><span/></div></div>}</section></div>
 {notices.length>0&&<section className="notice-panel"><h2><Info size={17}/>扫描说明 <span>{notices.length}</span></h2>{notices.map(p=><div key={p.url} className="notice-row"><a href={p.url} target="_blank" rel="noreferrer">{p.title}</a><p>{p.warnings.join('；')}</p></div>)}</section>}
 <footer><span>拾音 <span className="footer-divider">/</span> 让声音随行</span><span>每次最多 100 个网页 · 每包最多 100 个音频 / 3 GB</span></footer></main></div>;
}
